# -*- coding: utf-8 -*-
"""pencil_sketch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z25hl3QgO0hBb8a_nAnLc_uTj7grgs77
"""

from google.colab.patches import cv2_imshow

import cv2

img=cv2.imread('msd.jpg')

gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

d=cv2.resize(gray_image,(300,300),interpolation=cv2.INTER_LANCZOS4)

cv2_imshow(d)

img_invert=cv2.bitwise_not(d)

blurred = cv2.GaussianBlur(img_invert, (21, 21), 0)

def dog(x,y):
    return cv2.divide(x,255-y,scale=256.0)

final=dog(d,blurred)

cv2_imshow(final)

